### ISSUE TITLE
"casual" or "causal"?

### ISSUE THREAD

**Issue by soloice** [XMUNLP/XMUNMT#7]
In https://github.com/XMUNLP/XMUNMT/blob/0e1539b306c8027be2e86216688a107aaccfab8f/xmunmt/layers/attention.py#L22, there is a string literal "casual"（随意的）, do you mean "causal"（因果性的）?
I guess this mode is designed to prevent network from seeing future information, so it might be "causal" instead of "casual."

**Comment by soloice** [comment]
And why does function `attention_bias` expand a rank-2 tensor to rank-4?
https://github.com/XMUNLP/XMUNMT/blob/0e1539b306c8027be2e86216688a107aaccfab8f/xmunmt/layers/attention.py#L32

As far as I see, it's sufficient to return a rank-2 tensor. For example, in `rnnsearch.py`, you generated a rank-4 bias then squeeze it back to rank-2:
```
bias = layers.attention.attention_bias(mem_mask, "masking")
bias = tf.squeeze(bias, axis=[1, 2])
```
I don't really get it.

**Comment by Playinf** [comment]
Thank you for pointing out some typo errors in the codes. Some of the codes in this repository is derived from the Tensor2Tensor library. The attention bias in that library is a 4D tensor. For RNNsearch, the bias term need not to be 4D. I'll remove such confusing codes.

**Comment by soloice** [comment]
Thanks for your reply.
